services:
  - type: static
    name: research-group-frontend
    env: static
    plan: free
    staticPublishPath: .
    buildCommand: ""
    envVars:
      - key: SUPABASE_URL
        value: https://nsdmvgrbzvapavoljzni.supabase.co
      - key: SUPABASE_ANON_KEY
        value: ""
      - key: BACKEND_URL
        value: https://research-website-11j3.onrender.com
